[2022-09-18 03:03:07,472] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-17T03:00:00+00:00 [queued]>
[2022-09-18 03:03:07,524] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-17T03:00:00+00:00 [queued]>
[2022-09-18 03:03:07,526] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 03:03:07,527] {taskinstance.py:1018} INFO - Starting attempt 3 of 3
[2022-09-18 03:03:07,528] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 03:03:07,565] {taskinstance.py:1038} INFO - Executing <Task(BigQueryCheckOperator): check_query_big_query_table> on 2022-09-17T03:00:00+00:00
[2022-09-18 03:03:07,580] {standard_task_runner.py:51} INFO - Started process 29567 to run task
[2022-09-18 03:03:07,591] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'bigquery_dag', 'check_query_big_query_table', '2022-09-17T03:00:00+00:00', '--job-id', '252', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_bigquery.py', '--cfg-path', '/tmp/tmpbe8ojzwh']
[2022-09-18 03:03:07,603] {standard_task_runner.py:76} INFO - Job 252: Subtask check_query_big_query_table
[2022-09-18 03:03:07,732] {logging_mixin.py:103} INFO - Running <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-17T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-18 03:03:07,881] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=bigquery_dag
AIRFLOW_CTX_TASK_ID=check_query_big_query_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-17T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-17T03:00:00+00:00
[2022-09-18 03:03:07,889] {sql.py:87} INFO - Executing SQL check: 
           select id from githubarchive.day.20220914
        
[2022-09-18 03:03:07,952] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:120 DeprecationWarning: This method will be deprecated. Please use `BigQueryHook.get_client` method
[2022-09-18 03:03:07,957] {taskinstance.py:1396} ERROR - [Errno 2] No such file or directory: '/opt/airflow/dags/dags/support/quick-keel-213611-bfc0c6523d4e.json'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/sql.py", line 88, in execute
    records = self.get_db_hook().get_first(self.sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 147, in get_first
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 107, in get_conn
    service = self.get_service()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 122, in get_service
    http_authorized = self._authorize()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 280, in _authorize
    credentials = self._get_credentials()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 251, in _get_credentials
    credentials, _ = self._get_credentials_and_project_id()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 237, in _get_credentials_and_project_id
    delegates=delegates,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 309, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 238, in get_credentials_and_project
    credentials, project_id = self._get_credentials_using_key_path()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 286, in _get_credentials_using_key_path
    self.key_path, scopes=self.scopes
  File "/home/airflow/.local/lib/python3.6/site-packages/google/oauth2/service_account.py", line 234, in from_service_account_file
    filename, require=["client_email", "token_uri"]
  File "/home/airflow/.local/lib/python3.6/site-packages/google/auth/_service_account_info.py", line 72, in from_filename
    with io.open(filename, "r", encoding="utf-8") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/dags/support/quick-keel-213611-bfc0c6523d4e.json'
[2022-09-18 03:03:07,979] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=bigquery_dag, task_id=check_query_big_query_table, execution_date=20220917T030000, start_date=20220918T030307, end_date=20220918T030307
[2022-09-18 03:03:08,089] {local_task_job.py:118} INFO - Task exited with return code 1
[2022-09-18 18:40:48,925] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-17T03:00:00+00:00 [queued]>
[2022-09-18 18:40:49,060] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-17T03:00:00+00:00 [queued]>
[2022-09-18 18:40:49,063] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 18:40:49,065] {taskinstance.py:1018} INFO - Starting attempt 3 of 3
[2022-09-18 18:40:49,067] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 18:40:49,133] {taskinstance.py:1038} INFO - Executing <Task(BigQueryCheckOperator): check_query_big_query_table> on 2022-09-17T03:00:00+00:00
[2022-09-18 18:40:49,208] {standard_task_runner.py:51} INFO - Started process 1569 to run task
[2022-09-18 18:40:49,278] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'bigquery_dag', 'check_query_big_query_table', '2022-09-17T03:00:00+00:00', '--job-id', '319', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_bigquery.py', '--cfg-path', '/tmp/tmpt_1ffdun']
[2022-09-18 18:40:49,312] {standard_task_runner.py:76} INFO - Job 319: Subtask check_query_big_query_table
[2022-09-18 18:40:49,574] {logging_mixin.py:103} INFO - Running <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-17T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-18 18:40:50,190] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=bigquery_dag
AIRFLOW_CTX_TASK_ID=check_query_big_query_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-17T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-17T03:00:00+00:00
[2022-09-18 18:40:50,265] {sql.py:87} INFO - Executing SQL check: 
           select id from githubarchive.day.20220914
        
[2022-09-18 18:40:50,549] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:120 DeprecationWarning: This method will be deprecated. Please use `BigQueryHook.get_client` method
[2022-09-18 18:40:52,356] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:2052 DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2022-09-18 18:40:52,372] {bigquery.py:1510} INFO - Inserting job airflow_1663526452367183_06d2bf8b43be9b79a3e89edf3b53e367
[2022-09-18 18:41:47,345] {sql.py:90} INFO - Record: ['23992050950']
[2022-09-18 18:41:47,362] {sql.py:96} INFO - Success.
[2022-09-18 18:41:47,462] {taskinstance.py:1142} INFO - Marking task as SUCCESS. dag_id=bigquery_dag, task_id=check_query_big_query_table, execution_date=20220917T030000, start_date=20220918T184048, end_date=20220918T184147
[2022-09-18 18:41:48,167] {taskinstance.py:1195} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2022-09-18 18:41:48,451] {local_task_job.py:118} INFO - Task exited with return code 0
[2022-09-18 19:18:57,938] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-17T03:00:00+00:00 [queued]>
[2022-09-18 19:18:58,064] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-17T03:00:00+00:00 [queued]>
[2022-09-18 19:18:58,067] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 19:18:58,069] {taskinstance.py:1018} INFO - Starting attempt 3 of 3
[2022-09-18 19:18:58,070] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2022-09-18 19:18:58,140] {taskinstance.py:1038} INFO - Executing <Task(BigQueryCheckOperator): check_query_big_query_table> on 2022-09-17T03:00:00+00:00
[2022-09-18 19:18:58,160] {standard_task_runner.py:51} INFO - Started process 4239 to run task
[2022-09-18 19:18:58,237] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'bigquery_dag', 'check_query_big_query_table', '2022-09-17T03:00:00+00:00', '--job-id', '373', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_bigquery.py', '--cfg-path', '/tmp/tmptgndr7qe']
[2022-09-18 19:18:58,249] {standard_task_runner.py:76} INFO - Job 373: Subtask check_query_big_query_table
[2022-09-18 19:18:58,406] {logging_mixin.py:103} INFO - Running <TaskInstance: bigquery_dag.check_query_big_query_table 2022-09-17T03:00:00+00:00 [running]> on host 27377494ab8b
[2022-09-18 19:18:58,593] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Dave
AIRFLOW_CTX_DAG_ID=bigquery_dag
AIRFLOW_CTX_TASK_ID=check_query_big_query_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-17T03:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-17T03:00:00+00:00
[2022-09-18 19:18:58,600] {sql.py:87} INFO - Executing SQL check: 
           select id from githubarchive.day.20220914
        
[2022-09-18 19:18:58,676] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:120 DeprecationWarning: This method will be deprecated. Please use `BigQueryHook.get_client` method
[2022-09-18 19:18:59,756] {logging_mixin.py:103} WARNING - /home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py:2052 DeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2022-09-18 19:18:59,767] {bigquery.py:1510} INFO - Inserting job airflow_1663528739761028_06d2bf8b43be9b79a3e89edf3b53e367
[2022-09-18 19:19:00,363] {taskinstance.py:1396} ERROR - 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/quick-keel-213611/jobs?prettyPrint=false: Access Denied: Project quick-keel-213611: User does not have bigquery.jobs.create permission in project quick-keel-213611.

(job ID: airflow_1663528739761028_06d2bf8b43be9b79a3e89edf3b53e367)

             -----Query Job SQL Follows-----             

    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:           select id from githubarchive.day.20220914
   3:        
    |    .    |    .    |    .    |    .    |    .    |

(job ID: airflow_1663528739761028_06d2bf8b43be9b79a3e89edf3b53e367)

             -----Query Job SQL Follows-----             

    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:           select id from githubarchive.day.20220914
   3:        
    |    .    |    .    |    .    |    .    |    .    |
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/sql.py", line 88, in execute
    records = self.get_db_hook().get_first(self.sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 152, in get_first
    cur.execute(sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2639, in execute
    self.job_id = self.hook.run_query(sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2186, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/common/hooks/base_google.py", line 425, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1512, in insert_job
    job.result()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1159, in result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/base.py", line 628, in result
    self._begin(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/query.py", line 1069, in _begin
    super(QueryJob, self)._begin(client=client, retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/job/base.py", line 438, in _begin
    timeout=timeout,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/bigquery/client.py", line 640, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.6/site-packages/google/api_core/retry.py", line 184, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/_http.py", line 483, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 POST https://bigquery.googleapis.com/bigquery/v2/projects/quick-keel-213611/jobs?prettyPrint=false: Access Denied: Project quick-keel-213611: User does not have bigquery.jobs.create permission in project quick-keel-213611.

(job ID: airflow_1663528739761028_06d2bf8b43be9b79a3e89edf3b53e367)

             -----Query Job SQL Follows-----             

    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:           select id from githubarchive.day.20220914
   3:        
    |    .    |    .    |    .    |    .    |    .    |

(job ID: airflow_1663528739761028_06d2bf8b43be9b79a3e89edf3b53e367)

             -----Query Job SQL Follows-----             

    |    .    |    .    |    .    |    .    |    .    |
   1:
   2:           select id from githubarchive.day.20220914
   3:        
    |    .    |    .    |    .    |    .    |    .    |
[2022-09-18 19:19:00,420] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=bigquery_dag, task_id=check_query_big_query_table, execution_date=20220917T030000, start_date=20220918T191857, end_date=20220918T191900
[2022-09-18 19:19:00,577] {local_task_job.py:118} INFO - Task exited with return code 1
